name: App Service Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: web-inmeta-learn

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"

      # Install dependencies and build the app
      - name: Install dependencies and build
        run: |
          npm install --force
          npm run build

      # Prepare deployment files
      - name: Prepare deployment files
        run: |
          mkdir -p ./.next/standalone
          cp -R ./public ./.next/standalone/public
          cp -R ./.next/static ./.next/standalone/.next/static
          cp package.json ./.next/standalone/package.json

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: "production"
          package: ./.next/standalone