name: Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - main  
  workflow_dispatch:

env:
  WEBAPP_NAME: "medium-next-app-service-deploy"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      # Step 3: Install dependencies and build
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
          mkdir -p .next/standalone
          cp -R public .next/standalone/public
          cp -R .next/static .next/standalone/.next/static
          cp package.json .next/standalone/package.json

      # Step 4: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: "Production"
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          package: ./.next/standalone
